queue_rules:
  - name: default
    merge_method: squash
    branch_protection_injection_mode: queue
    queue_conditions:
      - "base = main"
      - "-draft"
      - "-conflict"
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - "github-review-approved"
      - "github-require-last-push-approval"
      - "github-code-owner-review-satisfied"
      - "check-success = Credo"
      - "check-success = Dependency Audit"
      - "check-success = Dialyzer"
      - "check-success = Docs Build"
      - "check-success = Format & Compile"
      - "check-success = Test"
    merge_conditions:
      - "base = main"
      - "-draft"
      - "-conflict"
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - "github-review-approved"
      - "github-require-last-push-approval"
      - "github-code-owner-review-satisfied"
      - "check-success = Credo"
      - "check-success = Dependency Audit"
      - "check-success = Dialyzer"
      - "check-success = Docs Build"
      - "check-success = Format & Compile"
      - "check-success = Test"

merge_protections_settings:
  reporting_method: check-runs
  auto_merge_conditions:
    - "base = main"

merge_protections:
  - name: default
    if:
      - "base = main"
    success_conditions:
      - "base = main"
      - "-draft"
      - "-conflict"
      - "#approved-reviews-by >= 1"
      - "#changes-requested-reviews-by = 0"
      - "github-review-approved"
      - "github-require-last-push-approval"
      - "github-code-owner-review-satisfied"
      - "check-success = Credo"
      - "check-success = Dependency Audit"
      - "check-success = Dialyzer"
      - "check-success = Docs Build"
      - "check-success = Format & Compile"
      - "check-success = Test"
