name: Publish Package
on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@v1.18.1
        with:
          elixir-version: "1.17" # [Required] Define the Elixir version
          otp-version: "27" # [Required] Define the Erlang/OTP version
      - name: Restore dependencies cache
        uses: actions/cache@v3
        with:
          path: deps
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-
      - name: Restore _build cache
        uses: actions/cache@v3
        with:
          path: _build
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.ex') }}
          restore-keys: ${{ runner.os }}-build-
      - name: Install dependencies
        run: mix deps.get
      - name: Check version
        run: |
          MIX_VERSION=$(grep 'version:' mix.exs | cut -d '"' -f2)
          TAG_VERSION=${GITHUB_REF/refs\/tags\/v/}
          if [ "$MIX_VERSION" != "$TAG_VERSION" ]; then
            echo "Tag version ($TAG_VERSION) does not match mix.exs version ($MIX_VERSION)"
            exit 1
          fi
      - name: Publish to Hex
        uses: synchronal/hex-publish-action@v3
        with:
          name: newt
          key: ${{ secrets.HEX_API_KEY }}
          tag-release: false
